---
env:
  contexts:
  - name: "FurahaProject"
    urls:
      - "https://staging.furaha.financial/"
    includePaths:
      - "https://staging.furaha.financial/.*"
    excludePaths: [ ]
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: { }
jobs:
# - type: addOns                       
#   parameters:
#     updateAddOns: false               
#   install:                           
#   - ascanrules
#   - openapi
- type: alertFilter
  alertFilters:
    - ruleId: 10021
      ruleName: "X-Content-Type-Options Header Missing"
      newRisk: "False Positive"
      url: "https://staging.furaha.financial/.*"
      urlRegex: true  
- type: openapi     # OpenAPI definition import via file
  parameters:
    apiFile: "/zap/wrk/openapi.json" #Path
    # apiUrl:   # String: URL containing the OpenAPI definition
    targetUrl: "https://staging.furaha.financial/auth/"
# - type: script
#   parameters:
#     action: "add"                  
#     type: "httpsender"                    
#     engine: "Oracle Nashorn"                 
#     # name: "GetToken"                 
#     # file: "/zap/wrk/scripts/GetToken.js"
- name: "activeScan"
  type: "activeScan"
  policyDefinition:
    rules: []
- parameters:
    template: "traditional-xml"
    reportDir: "/zap/wrk"
    reportFile: "furahaXmlReport"
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
    displayReport: false
  risks:
    - "info"
    - "low"
    - "medium"
    - "high"
  confidences:
    - "low"
    - "medium"
    - "high"
    - "confirmed"
  name: "xmlreport"
  type: "report"
- parameters:
    template: "traditional-html"
    # theme: "original"
    reportDir: "/zap/wrk"
    reportFile: "furahaHtmlreport"
    reportTitle: "ZAP Scanning Report"
    # reportDescription: ""
    displayReport: false
  risks:
  - "info"
  - "low"
  - "medium"
  - "high"
  confidences:
  - "falsepositive"
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  # sections:
  # - "siteRiskCounts"
  # - "responseBody"
  # - "appendix"
  # - "alertTypes"
  # - "responseHeader"
  # - "alertTypeCounts"
  # - "riskConfidenceCounts"
  # - "alerts"
  # - "aboutThisReport"
  # - "contents"
  # - "requestBody"
  # - "reportDescription"
  # - "reportParameters"
  # - "requestHeader"
  # - "summaries"
  name: "htmlreport"
  type: "report"
