name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install OWASP ZAP
      run: |
        sudo apt-get update
        sudo apt-get install zaproxy

    - name: Install Python dependencies
      run: pip install python-owasp-zap-v2.4

    - name: Run ZAP scan
      env:
        ZAP_API_KEY: ${{ secrets.ZAP_AUTH_HEADER_VALUE }}  # Add your ZAP API key to GitHub Secrets
      run: |
        zap.sh -daemon -config api.key=${{ secrets.ZAP_AUTH_HEADER_VALUE }} -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true &
        sleep 30
        python your_scan_script.py
