name: CD-auth-service
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  DeployDev:
    environment:
      name: Dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: auth-service
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
  zap_scan:
    runs-on: ubuntu-latest
    name: DAST Scan
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: '${{ secrets.DEV_BASE_URL }}'
          allow_issue_writing: false
 
  
