name: OWASP ZAP API Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run OWASP ZAP scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw -t zaproxy/zap2docker-stable \
          zap.sh -cmd -autorun /zap/wrk/plans/plan.yaml
          # docker run -v $(pwd):/zap/wrk/:rw  --user root  softwaresecurityproject/zap-stable python3 /zap/zap-api-scan.py \
          # -t openapi.json -J dast-report.json -d -r dast-report.html -I -S -f openapi -z options.propsoftwaresecurityproject/zap-stable \
          # python3 /zap/zap-api-scan.py -t swagger.yaml -J dast-report.json -d -r dast-report.html -I -S -f openapi -z options.prop
          # docker run --rm -v $(pwd):/zap/wrk/:rw -t zaproxy/zap-stable zap-api-scan.py \
          # -t openapi.json -f openapi
            # -t https://staging.furaha.financial/ \
            # -f openapi \
            # -r testreport.html
            # -t https://develop.furaha.financial/auth/v1/auth/login \
            # -t https://develop.furaha.financial/auth/v1/auth/signup \

      - name: Upload OWASP ZAP report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: dast-report.html
