name: CD-auth-service
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  DeployDev:
    environment:
      name: Dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: auth-service
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://staging.furaha.financial/auth/'

