name: CD-auth-service
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  DeployDev:
    environment:
      name: Dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: auth-service
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
  zap_scan:
    runs-on: ubuntu-latest
    name: DAST Scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log current directory
        run: echo ${pwd}
      - name: Pull ZAP OWASP Image
        run: docker pull zaproxy/zap-stable 
      # - name: copies json file
      #   run: cp
      - name: Run ZAP API Scan
        run: |
          sudo docker run -v  $(pwd):/zap/wrk/:rw -t zaproxy/zap-stable zap-api-scan.py -t https://staging.furaha.financial/openapi.json -
          # f openapi -c api-scan.conf
      # - name: ZAP Scan
      #   uses: zaproxy/action-baseline@v0.12.0
      #   with:
      #     target: ${{vars.DEV_BASE_URL}}
      #     allow_issue_writing: false
