name: CD-auth-service
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  DeployDev:
    environment:
      name: Dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: auth-service
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
    services:
     zap:
      image: zaproxy/zap-stable
      ports:
       - 8080:8080
      options: >-
       --entrypoint=/bin/sh zap
       -c "zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=changeme"
      
        - name: Wait for API to be available
        run: |
          echo "Waiting for API to be available..."
          for i in `seq 1 30`; do
            curl -sSf {{ secrets.DEV_BASE_URL }}/auth/ && break
            echo "Waiting for API to be available..."
            sleep 5
          done
         - name: Run OWASP ZAP Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw --user root --network="host" zaproxy/zap-stable zap-baseline.py -t {{ secrets.DEV_BASE_URL }}/auth/ -r zap_report.html -I
        - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html

