name: CD-auth-service

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  DeployDev:
    environment:
      name: Dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: auth-service
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
  zap_scan:
    runs-on: ubuntu-latest
    name: DAST Scan
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ vars.DEV_BASE_URL }}
          allow_issue_writing: false
          rules_file: 'zap-rules.txt'
          config: |
            replacer.full_list(0).description=auth1
            replacer.full_list(0).enabled=true
            replacer.full_list(0).matchtype=REQ_HEADER
            replacer.full_list(0).matchstr=Authorization
            replacer.full_list(0).regex=false
            replacer.full_list(0).replacement=123456789
            replacer.full_list(1).description=auth2
            replacer.full_list(1).enabled=true
            replacer.full_list(1).matchtype=REQ_HEADER
            replacer.full_list(1).matchstr=AnotherHeader
            replacer.full_list(1).regex=false
            replacer.full_list(1).replacement=abcdefghi
